### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fkrisi11** [SuperMartijn642/MovingElevators#12]
Can you have 2 seperate elevators, with the controllers having the same X, Z coordinates?
Like... 2 seperate elevators above each other.

**Comment by SuperMartijn642** [comment]
![image](https://user-images.githubusercontent.com/12382965/79910989-eb9cdd00-841f-11ea-94e1-363b9b5e5ba5.png)
For the colors you simply right click a floor button with a dye.
You can have two separate elevators on the same x and z if they are facing in different directions. You can't have two elevators facing the same way though due to how the mod works.
Edit: seems it doesn't wanna do the gif, you can see it here in the description, https://www.curseforge.com/minecraft/mc-mods/moving-elevators

**Comment by fkrisi11** [comment]
Yeah I felt a bit silly after seeing that you explained colors quite well in CurseForge post already...
I really like that feature actually ^^

Also, thanks for the explanation.
That's everything I wanted to know.

This mod is getting better and better each update ^^

**Comment by SuperMartijn642** [comment]
Yeah no worries :)
