### ISSUE TITLE
[Bug] Elevator Disguise not showing the right block texture in 1.12.2

### ISSUE THREAD

**Issue by Shoutin9Quasar3** [SuperMartijn642/MovingElevators#125]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.3.7
- SuperMartijn642's Config Lib, 1.0.9a
- SuperMartijn642's Core Lib, 1.0.18
(Just these 3 mods only)

**Are you using OptiFine?**: No

**Description of the Bug**
When righting clicking an elevator controller or display with a block in your hand, it doesn't show the right texture.

**Screenshots**
Movingelevators-1.3.7 (movingelevators 1.3.0-1.36 don't work either)
![1 12 2 movingelevators-1 3 7](https://user-images.githubusercontent.com/16888297/169569962-3ba4a2c6-9ea2-44ad-85fa-5b85c59f2279.gif)

Movingelevators-1.2.34 or below works fine
![1 12 2 movingelevators-1 2 34](https://user-images.githubusercontent.com/16888297/169569752-bfbe8509-30d8-4c62-a665-207f966cbc21.gif)

**Comment by SuperMartijn642** [comment]
I probably messed this up when porting the 1.3.0 version from 1.14+ to 1.12, since 1.14+ don't have metadata.
I already fixed this once before as well, but I guess I made the same mistake again and forgot about metadata 🤦‍♂️

No clue when I'll have time to work on mods again, so might be a while before I get around to fixing this.

**Comment by SuperMartijn642** [comment]
I fixed the issue now in Moving Elevators 1.3.9 for Minecraft 1.12.
Thank you for reporting the issue!
