### ISSUE TITLE
[Crash] The ME 1.3.7 make a watchdog crash and interrupt chunk spawn

### ISSUE THREAD

**Issue by HMSRenown** [SuperMartijn642/MovingElevators#130]
**Version Info**
- Minecraft, 1.16.5
- Moving Elevators, 1.3.7

**Are you using OptiFine?**: Yes

**Bug Discrption**
I use moving elevator in my server,but it makes a watchdog crash.
And locked some chunks in my save.
When I remove Moving Elevators 1.3.7,everything is ok.

**Steps to Reproduce**
1.Start a server with a Spigot Core
2.Make an Elevator
3.Let anothoer player login

Please fix this bug.
Your elevator mod is the most useful and excellent elevator mod in Minecraft.
I can't find any mod instead of it.

**Crash report (~/logs/latest.log)**
[2022-06-20-1.log.zip](https://github.com/SuperMartijn642/MovingElevators/files/8936811/2022-06-20-1.log.zip)

**Comment by SuperMartijn642** [comment]
I cannot reproduce this issue on a regular Forge server.
You seem to be using some sort of Spigot and Forge combination server. These kinds of servers usually lead to weird crashes because their implementation is different from Forge's. Sadly, I cannot support these kinds of servers.

Please report the issue to the server software you are using.
