### ISSUE TITLE
[Feature] Fabric Support

### ISSUE THREAD

**Issue by TheCherry** [SuperMartijn642/MovingElevators#140]
**Is your feature request related to a problem? Please describe.**
Would be nice to get Fabric support.

**Describe the solution you'd like**
An Simple Example to implement would be maybe the Clumps Mod: https://github.com/jaredlll08/Clumps
They can "cross" compile it for fabric and forge.

**Comment by vanja-san** [comment]
[Serilum](https://modrinth.com/user/Serilum) a good example of how to make one file for multiple loaders.

**Comment by SuperMartijn642** [comment]
I've had a fabric version of my core and config libraries, and Entangled for over a year now. I just wanted to expand on my core library first to make developing my other mods for Fabric easier. That took far longer than expected since I just don't have a lot of time available.
The update for my core library is done now. Next I will be updating my mods to 1.19.3 and after that, I will port all my mods to Fabric.
Of course bugs that come up take priority and I just don't have a lot of time due to school and sports, so everything takes a while.
