### ISSUE TITLE
[Crash] Stuck at Preparing spawn area: (random)%

### ISSUE THREAD

**Issue by Flyrder** [SuperMartijn642/MovingElevators#148]
If the mods folder have the elevator mod 
The server will definitely stucks
![Screenshot_2022-12-11-10-58-37-887_com termux-edit](https://user-images.githubusercontent.com/106471753/206884251-403fb4b8-270b-4e4d-9a8e-e5a20480aa84.jpg)

OS Info:
Server: Mohist 1.16.5 Ver1077
Platform: Arm64

**Comment by SuperMartijn642** [comment]
Please fill in the template properly. What version of Moving Elevators are you using? Could you upload the `~/logs/latest.log` log file? What other mods are you using?

Additionally, hybrid bukkit-forge servers like Mohist often lead to problems because they break common assumptions about how stuff works. I likely won't change anything if the issue cannot be reproduced with a regular Forge server.
