### ISSUE TITLE
[Bug] 1.12.2 Elevator disappears at dimensions, registred by just enough dimensions

### ISSUE THREAD

**Issue by Avventis90005** [SuperMartijn642/MovingElevators#157]
**Version Info**
- Minecraft: 1.12.2
- Moving Elevators: movingelevators-1.3.11-forge-mc1.12

**Are you using OptiFine?**: Yes

**Description of the Bug**
Elevator controller GUI does not work at dimensions other, than -1, 0 and 1 (buttons at GUI do nothing. There is a "click" sound, but values stay the same. Only "speed" slider still works). Also dimensions, other, than -1, 0 and 1 elevator is disappears (not invisible, physically disappears) while moving. 
Bug first time appeared, when i'm updated just enough dimensions mod to "justenoughdimensions-1.12.2-1.6.0-dev.20211009.214847". But doesn't disappear if i'm back to previous version. 

Removing optifine doesn't solve the problem.
It seems, like elevator entity spawns at wrong place... 

**Steps to Reproduce**
Build an elevator at -1, 0 or 1 dimension - elevators is not invisible, and GUI is works fine. Build an elevator at 500, 501 or any other dimension - elevator cannot be configured, and disappears, while moving.

**Screenshots**
There is nothing to screenshot +( I'm literrally cannot screenshot invisible elevator or not working buttons.

**Comment by SuperMartijn642** [comment]
It seems the `DimensionType` obtained from Just Enough Dimension's dimensions has an incorrect dimension id. The dimension id is used to send packets with elevator data to all players in the dimension with the given dimension id. Since the id was incorrect, packets weren't sent to the correct dimension.
Nonetheless, I fixed it now by taking the dimension id directly from the `WorldProvider` object instead of the `DimensionType`.

The fix is available in version 1.1.6a of my core library for Minecraft 1.12.
Thank you for reporting the issue!
