### ISSUE TITLE
[Crash] Embeddium Issue

### ISSUE THREAD

**Issue by Airisii** [SuperMartijn642/MovingElevators#186]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.3a

**Are you using OptiFine?**: no

**Steps to Reproduce**
Install Moving Elevators and Embeddium (plus dependencies)
Launch game

**Crash report (~/logs/latest.log)**
[crash-2023-09-03_18.10.45-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/12507946/crash-2023-09-03_18.10.45-client.txt)

Also it affects both rubidium 0.7 and embeddium. Older versions of rubidium such as 0.6.5 work fine.

**Comment by SuperMartijn642** [comment]
It already works fine with Rubidium 0.7.

The error is caused by the fact that [this method](https://github.com/embeddedt/embeddium/blob/c2cd2b644d6592e1057dff5262438d7f98e81d73/src/main/java/me/jellysquid/mods/sodium/client/render/SodiumWorldRenderer.java#L258) is called `renderBlockEntities` in Embeddium while it is called `renderTileEntities` in Rubidium.

Moving Elevators 1.4.3c for Forge on 1.20 will now check for both methods.
Thank you for reporting the issue!
