### ISSUE TITLE
[Crash] Weird crash from breaking elevator controller

### ISSUE THREAD

**Issue by ninjakitty844** [SuperMartijn642/MovingElevators#190]
**Version Info**
- Minecraft, 1.12.2
- Moving Elevators, 1.4.3

**Are you using OptiFine?**: yes

**Steps to Reproduce**
1. Make an elevator with 3 floors
2. Have elevator at top floor
3. Break the middle floor elevator controller
4. It crashes almost instantly every time

**Crash report (~/logs/latest.log)**
[crash-2023-09-22_18.33.43-client.txt](https://github.com/SuperMartijn642/MovingElevators/files/12705220/crash-2023-09-22_18.33.43-client.txt)

**Post-crash glitches:**
After this crash, the world was now glitched. Entities and blocks would rapidly switch between being visible and invisible.
Both of these screenshots are taken from the same location, milliseconds apart:
![2023-09-22_18 37 17](https://github.com/SuperMartijn642/MovingElevators/assets/89247988/2127ef6e-6244-42e5-8309-2617a6d78d48)
![2023-09-22_18 37 19](https://github.com/SuperMartijn642/MovingElevators/assets/89247988/ae314263-aee4-40b2-a927-8a335ec3f749)
These graphical glitches were fixed only after I deleted all my elevators and restarted Minecraft.

**Comment by SuperMartijn642** [comment]
Not exactly sure how that crash happened as I couldn't reproduce it, even with remote elevator panels for each floor. Nonetheless, I added an additional check for the remote elevator panel to prevent the scenario in the crash log from happening.

> After this crash, the world was now glitched.

I am not sure how this would be caused by Moving Elevators and is likely caused by some other mod you have installed.
If you want, you can delete `data/capabilities.dat` inside the world folder for whichever world the crash happened in, to reset the elevator data. Note that this deletes the data for any world capabilities including those from other mods, so make sure to make a backup of your save beforehand.

The changes are available in Moving Elevators version 1.4.4. Thank you for reporting the issue.
