### ISSUE TITLE
[Crash] Crash on startup in 1.14.4

### ISSUE THREAD

**Issue by RichKeo** [SuperMartijn642/MovingElevators#223]
**Version Info**
- Minecraft, 1.14.4
- Moving Elevators, 1.4.7

**Are you using OptiFine?**: nop

**Steps to Reproduce**
only launch the game

**Crash report (~/logs/latest.log)**
[crash-2024-06-20_18.57.43-client.txt](https://github.com/user-attachments/files/15920547/crash-2024-06-20_18.57.43-client.txt)

**Comment by SuperMartijn642** [comment]
On 1.14 you'll have to use [MixinBootstrap](https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap) since Forge only started including mixin in 1.15.
MixinBootstrap is not marked as a dependency on CurseForge as CurseForge will then show it under the 'relations' tab as a dependency, confusing people on modern versions. 1.14 is by far the least played version, so I think it is a fair trade-off.
I also looked into marking MixinBootstrap as a dependency in the mod file, but since MixinBootstrap doesn't actually include a mod (only a launch service for ModLauncher) there is no modid to add a dependency for.
