### ISSUE TITLE
[Crash] Moving Elevators crashes on startup with Optifine

### ISSUE THREAD

**Issue by SpeedRacer00** [SuperMartijn642/MovingElevators#235]
**Version Info**
- Minecraft, 1.20.1
- Moving Elevators, 1.4.8

**Are you using OptiFine?**: Yes

**Steps to Reproduce**
1. Just have Optifine and Moving Elevators as the only mods in your mod folder
2. Crashes on startup

**Crash report (~/logs/latest.log)**
https://securelogger.net/files/67296386-b5fc-4618-abc0-7552d60803e2.txt

**Comment by SuperMartijn642** [comment]
OptiFine changes many parts of the game often leading to bugs or crashes. Because OptiFine is closed source, I cannot know what they change and there is not much I can do about compatibility issues. Feel free to report the issue to them.
I would suggest using alternatives like [Iris](https://modrinth.com/mod/iris) or [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus).
