### ISSUE TITLE
[Bug] Model gap in elevator blocks texture

### ISSUE THREAD

**Issue by Anonyku05** [SuperMartijn642/MovingElevators#251]
**Version Info**
- Minecraft, 1.20.4
- Moving Elevators, 1.4.10

**Are you using OptiFine?**: No

**Description of the Bug**
Basically there is a model gap in the elevator blocks textures

**Steps to Reproduce**
1. Place one of the elevators blocks
2. That's it

**Screenshots**
![2024-11-10_19 48 12](https://github.com/user-attachments/assets/9715672c-c33e-4275-ac0b-78974e1a4ee3)

Idk if this issue is "normal" since i have a mod that is supposed to fix all model gap (this [one](https://modrinth.com/mod/modelfix)

**Comment by SuperMartijn642** [comment]
It is not a model gap, it is caused by the block highlight. This happens for any translucent blocks. You can see this when looking at stained glass as well for example. If you disable the hud with F1 or look slightly to next to the block rather than at it, you should be able to see that there's no gap.
You can fix the translucency issue by using the fabulous rendering setting.
