### ISSUE TITLE
Bug when the elevator moves past negative values in cubic chunks

### ISSUE THREAD

**Issue by Mysticpasta1** [SuperMartijn642/MovingElevators#37]
**Version Info**
movingelevators-1.2.24-mc1.12
cubic chunks version 1153 for 1.12.2
cubic world generation 131 for 1.12.2
- Minecraft, 1.12.2 forge 2847
- Chunk Loaders, none

**Description of the Bug**
when switching from a negative height to a positive height it disappears and make you fall off of it

**Steps to Reproduce**
make a elevator from y = -90 to y = 68 and go up and down a few time with the mod/mods said.

**Screenshots**
no screenshot shown, due to how to screenshot a invisible object that reappear when moved

**Comment by SuperMartijn642** [comment]
Oops I forgot to change Chunk Loaders to Moving Elevators... 🤦‍♂️

I didn't realize Cubic Chunks went below y=0 even though that's pretty obvious when I think about it. I'm surprised it works at all since I basically assumed it's position was at the lowest y=0.
I will look into it and it will probably be fixed either today or tomorrow.

**Comment by SuperMartijn642** [comment]
1.
So the problem seems to be that the vertical chunks in Cubic Chunks can load and unload independently of each other. I tick, save and load the entire group of elevator controllers when the lowest one in the group does so.
When you go up with the elevator the bottom controller can get unloaded and thus the elevator doesn't get ticked anymore.

This is also the cause for the buttons not appearing when the bottom elevator controller is unloaded.

I can fix this, but it requires a rewrite for the elevator group code and will take more time than I expected. As of right now I don't have an ETA for when this will be done.

2.
Apart from this, Tick Dynamic can also cause the elevator to not get ticked for a couple of ticks, which can let players fall through.
This I cannot fix, thus Moving Elevators will always have some issues when combined with Tick Dynamic.

**Comment by Mysticpasta1** [comment]
thanks and I removed tick dynamic 👍

**Comment by SuperMartijn642** [comment]
The elevators are now completely handled with a world capability and not by tile entities. This way it doesn't require the tile entities to be loaded.
It should now work fine with Cubic Chunks, as of version 1.2.25.

Thank you for reporting the issue and helping me narrow down the problem!
