### ISSUE TITLE
[Crash] Mixin Transformer Error

### ISSUE THREAD

**Issue by Yourname942** [SuperMartijn642/MovingElevators#58]
**Version Info**
Minecraft 1.16.5
Forge 36.1.2
Moving Elevators 1.2.34
Create mc1.16.5_v0.3.1c

**Steps to Reproduce**
1. Launch CurseForge App
2. Launch Minecraft
3. Crash 

**Crash report (~/logs/latest.log)**
Crash Log:
https://gist.github.com/Yourname942/1c085a384bccc3db8430324609a23019
Latest Log:
https://gist.github.com/Yourname942/d6702e89d2fcaf150d44190f1a4e765b

For some reason the game crashed sometime while booting up Minecraft. This is happening every time I boot up minecraft now..
![1](https://user-images.githubusercontent.com/58750222/117551363-97a56c00-b013-11eb-83a9-8052fbf9fa36.jpg)

**Comment by SuperMartijn642** [comment]
Minecraft launches without errors for me with the versions of Forge, Create, and Moving Elevators you specified. It is probably some other mod interfering.

If you go to your profile in the CurseForge launcher, there's an option called 'Export Profile'. Could you send me those exported files? That way I don't to download all of the mods individually, since you have quite a lot of mods installed.

**Comment by Yourname942** [comment]
Hmm. Yes here you go: [SurvivalWorldPlus-1.zip](https://github.com/SuperMartijn642/MovingElevators/files/6446486/SurvivalWorldPlus-1.zip)

**Comment by Yourname942** [comment]
Any ideas?

**Comment by SuperMartijn642** [comment]
The mod causing issues seems to be Random Patches.

**Comment by SuperMartijn642** [comment]
Removing Moving Elevators, Create, and Create Additions still results in a crash.

However removing just Random Patches, the game starts up without crashing.
I would suggest reporting the issue to them.
