### ISSUE TITLE
[Bug] Elevator Display isn't rendered correctly anymore since latest update using Shaders

### ISSUE THREAD

**Issue by Zothen1973** [SuperMartijn642/MovingElevators#59]
**Version Info**
- Minecraft, 1.16.5, Forge 36.1.16
- Moving Elevators, ...1.2.34
- Nostalgic Shaders 3.0

![2021-05-12_21 49 54](https://user-images.githubusercontent.com/77007295/118036173-88eceb00-b36c-11eb-8566-f82cb30834cc.png)

**Comment by Zothen1973** [comment]
Sorry, false alarm. After a few seconds ingame, the panel renders just fine.

**Comment by SuperMartijn642** [comment]
Ah glad it works now 🙂

**Comment by AngleWyrm10** [comment]
Just updated to latest version of Java, and now I'm getting something that looks like text shadowing that makes it hard to read.

If it is a text shadow effect, is it possible to turn off?

![textOddity](https://user-images.githubusercontent.com/55937426/123338202-44bd4080-d4fd-11eb-8fd3-4e2eeeb83faf.png)

**Comment by SuperMartijn642** [comment]
Java version doesn't affect it.

I don't remember if I used text with or without shadows. I'll have a look next time I work on Moving Elevators.

What version of Minecraft and Moving Elevators are you using?

**Comment by AngleWyrm10** [comment]
Minecraft: v1.16.5
Moving Elevators: v1.2.34-mc1.16.5
Optifine: [v1.16.5 HD U G8](https://optifine.net/adloadx?f=OptiFine_1.16.5_HD_U_G8.jar)
Shader: Complementary Shaders [v4.0.2](https://www.curseforge.com/minecraft/customization/complementary-shaders/files/3331442)
Java: [v1.8.0_291-b10](https://www.java.com/download/ie_manual.jsp)

---
I had received a warning about old Java version and text rendering when I accidentally added a 1.12 version mod to my collection (it was [Integrated Foregoing](https://www.curseforge.com/minecraft/mc-mods/integration-foregoing)) After removing that wrong-version mod and updating Java the warning went away. Since you say Java version doesn't affect it, I can only guess that feature has been integrated for a long time.

**Comment by SuperMartijn642** [comment]
Nearly all of Moving Elevators rendering has been redone in Moving Elevators 1.3.0. Please open a new issue if this still happens with Moving Elevators 1.3.0.
