### ISSUE TITLE
[Feature] Untraversable Block for Elevators

### ISSUE THREAD

**Issue by ExDomino** [SuperMartijn642/MovingElevators#67]
Hello,

My idea is creating an untraversable block that if placed between two elevator controller, the elevator would refuses to travel between these two floors. Useful for example for placing an elevator inside a SecurityCraft base and preventing anyone to get inside the base in creating a new floor and use the elevator to enter/exit. This block should be placed at the same coordinate than elevator floor controlers.

Thank you in advance!

**Comment by SuperMartijn642** [comment]
The main problem this would solve is having two separate elevators in the same x-z column. An untraversable block seems like a bit of a clumsy solution. I would probably just make it configurable in the elevator controller's gui, however implementing this would make the underlying code quite a bit more complex.

Since Moving Elevators 1.3.0, you can now offset the elevator cabin from the elevator controller. This means you can have two elevator systems in the same location above each other simply by offsetting the cabin for one of them.
Since I don't want to overhaul the underlying code and I feel there's an easy enough alternative, I will be closing the issue.
